# -*- coding: utf-8 -*-
"""Proyek Analisis Data_M002B4KX3191_Nabilla Oktabania Pratiwi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRqmfYGARpy0jqjI0pHxU31t-tAjoOsy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Nabilla Oktabania Pratiwi
- **Email:** M002B4KX3191@bangkit.academy
- **ID Dicoding:** M002B4KX3191

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Apakah jumlah penggunaan sepeda lebih tinggi pada hari libur dibandingkan dengan hari kerja?
- Pertanyaan 2 : Apakah cuaca memengaruhi permintaan penggunaan sepeda?
- Pertanyaan 3 : Bagaimana tren penggunaan sepeda dari waktu ke waktu?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

data = 'https://raw.githubusercontent.com/Nabillaop/M002B4KX3191_Nabilla-Oktabania-Pratiwi/refs/heads/main/day.csv' # Mengimport data dari github
data_hari = pd.read_csv(data) # Mendefinisikan data permintaan penggunaan sepeda per hari
data_hari # Menampilkan data permintaan penggunaan sepeda perhari

"""**Insight:**
- Terdapat dataset day.csv yang berisi data peminjaman sepeda selama 731 hari (dari tanggal 01-01-2011 hingga 31-12-2012).
- Pada data tersebut terdapat kolom yang memuat informasi diantaranya adalah:
  - instant (nomor urut setiap hari),
  - dteday (tanggal spesifik untuk data harian),
  - season (1 spring, 2 summer, 3 fall, 4 winter),
  - year (0 untuk 2011, dan 1 untuk 2012),
  - mnth (angka 1-12 merepresentasikan bulan januari-desember),
  - holiday (indikator hari libur, dengan 0 bukan hari libur dan 1 hari libur),
  - weekday (0-6 yang berarti hari senin hingga minggu),
  - workingday (indikator apakah hari kerja atau bukan, 0 bukan hari kerja, 1 hari kerja),
  - weathersit (kategori kondisi cuaca, 1 cuaca cerah, 2 mendung, 3 hujan),
  - temp (suhu normalisasi, 0-1 dengan 0 terendah),
  - atemp (suhu terasa),
  - hum (kelembaban),
  - windspeed (kecepatan angin),
  - casual (jumlah pengguna yang menggunakan sepeda sesekali),
  - registered (jumlah pengguna terdaftar),
  - cnt (jumlah pengguna total).

### Assessing Data
"""

#menampilkan informasi mengenai tipe data untuk data hari
print(data_hari.info())

#memeriksa missing values untuk data hari
print(data_hari.isna().sum())

#memeriksa duplikasi data untuk data hari
print("Jumlah duplikasi: ", data_hari.duplicated().sum())

# statistik deskriptif dari data untuk data hari
print(data_hari.describe())

"""**Insight:**
- Berdasarkan output di atas, tidak terdapat missing value ataupun data duplikat pada dataset.

### Cleaning Data
"""

# Data tidak memiliki missing value ataupun data duplikat, ini hanya contoh saja jika data belum clean
data_hari.drop_duplicates(inplace=True) #mengatasi data duplikat
data_hari[data_hari.isna()] #mengatasi missing value

# Memilih hanya kolom numerik untuk pengolahan data berikutnya
data_numerik = data_hari.select_dtypes(include=['float64', 'int64'])
data_numerik

"""**Insight:**
- Data sudah bersih, tidak perlu melakukan cleaning data untuk menghilangkan data duplikat ataupun mengatasi missing value.
- Note: kode tetap dituliskan walaupun tidak digunakan pada kasus data penggunaan sepeda harian.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# statistik deskriptif dari data
data_hari.describe(include="all")

data_hari.hist(figsize=(17, 12)) # Menampilkan histogram dari data berdasarkan masing-masing parameter
plt.show() # Menampilkan histogram

# Menghitung korelasi antara cnt dengan semua kolom lainnya
cnt_corr = data_numerik.corr()['cnt'].sort_values(ascending=False)
print("korelasi antara cnt dan variabel lain:")
print(cnt_corr)

"""**Insight:**
- min cnt (total pengguna sepeda) sebanyak 22, dan maks cnt sebanyak 8714, dengan mean 4504.348837.
- Dapat dilihat bahwa faktor dari cuaca seperti temp dan atemp memiliki korelasi yang cukup kuat dengan cnt (total penggunaan sepeda), sedangkan faktor hum dan windspeed memiliki korelasi yang lemah dengan cnt.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Menghitung total penggunaan sepeda berdasarkan workingday
cnt_workingday = data_hari.groupby('workingday')['cnt'].sum().reset_index()

# Membuat bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='workingday', y='cnt', data=cnt_workingday)
plt.title('Total Penggunaan Sepeda')
plt.xlabel('Hari')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.xticks([0, 1], ['Akhir Pekan', 'Hari Kerja'])
plt.show()

# menghitung rata-rata penggunaan sepeda berdasarkan hari kerja
plt.figure(figsize=(10, 5))
sns.barplot(x='workingday', y='cnt', data=data_hari, color='red')
plt.title('Rata-Rata Penggunaan Sepeda')
plt.xlabel('Hari Kerja')
plt.ylabel('Rata-Rata Jumlah Penggunaan Sepeda')
plt.xticks([0, 1], ['Akhir Pekan', 'Hari Kerja'])
plt.show()

# Mengubah kolom dteday menjadi tipe datetime
data_hari['dteday'] = pd.to_datetime(data_hari['dteday'])

# Menambahkan kolom hari dalam seminggu
data_hari['hari_dalam_seminggu'] = data_hari['dteday'].dt.day_name()
hari= {
    'Monday': 'Senin',
    'Tuesday': 'Selasa',
    'Wednesday': 'Rabu',
    'Thursday': 'Kamis',
    'Friday': 'Jumat',
    'Saturday': 'Sabtu',
    'Sunday': 'Minggu'
}

data_hari['hari_dalam_seminggu'] = data_hari['hari_dalam_seminggu'].map(hari)

# Mengelompokkan dan menghitung total penggunaan sepeda per hari
cnt_harian = data_hari.groupby('hari_dalam_seminggu')['cnt'].sum().reindex(['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']).reset_index()

# Membuat bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='hari_dalam_seminggu', y='cnt', data=cnt_harian, color='green')
plt.title('Total Penggunaan Sepeda Berdasarkan Hari dalam Seminggu')
plt.xlabel('Hari dalam Seminggu')
plt.ylabel('Total Penggunaan Sepeda')
plt.show()

# Menghitung total penggunaan sepeda berdasarkan musim
cnt_season = data_hari.groupby('season')['cnt'].sum().reset_index()

# Mapping angka musim menjadi nama musim
cnt_season['season'] = cnt_season['season'].map({
    1: 'Musim Semi',
    2: 'Musim Panas',
    3: 'Musim Gugur',
    4: 'Musim Dingin'
})

# Membuat bar chart
plt.figure(figsize=(8, 5))
sns.barplot(x='season', y='cnt', data=cnt_season, color='purple')
plt.title('Total Penggunaan Sepeda Berdasarkan Musim')
plt.xlabel('Musim')
plt.ylabel('Total Penggunaan Sepeda')
plt.show()

"""### Pertanyaan 2:"""

# Menghitung total penggunaan sepeda berdasarkan kondisi cuaca
cnt_cuaca = data_hari.groupby('weathersit')['cnt'].sum().reindex([0, 1, 2, 3]).reset_index()

# Mapping kondisi cuaca menjadi nama dalam bahasa Indonesia
cuaca_mapping = {
    1: 'Cuaca Cerah',
    2: 'Cuaca Mendung',
    3: 'Hujan',
}

# Mengganti nilai numerik cuaca dengan nama cuaca
cnt_cuaca['weathersit'] = cnt_cuaca['weathersit'].map(cuaca_mapping)

# Membuat bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='weathersit', y='cnt', data=cnt_cuaca)
plt.title('Total Penggunaan Sepeda Berdasarkan Kondisi Cuaca')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Total Penggunaan Sepeda')
plt.show()

#Scatterplot untuk hubungan antara suhu normalisasi dan penggunaan sepeda
plt.figure(figsize=(10, 6))
sns.scatterplot(x='temp', y='cnt', data=data_hari, alpha=0.6)
plt.title('Hubungan antara Suhu dan Penggunaan Sepeda')
plt.xlabel('Suhu (normalisasi)')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.grid()
plt.show()

#Scatterplot untuk hubungan antara suhu terasa dan penggunaan sepeda
plt.figure(figsize=(10, 6))
sns.scatterplot(x='atemp', y='cnt', data=data_hari, alpha=0.6, color ='purple')
plt.title('Hubungan antara Suhu dan Penggunaan Sepeda')
plt.xlabel('Suhu (terasa)')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.grid()
plt.show()

#Scatterplot untuk hubungan antara Kelembaban dan penggunaan sepeda
plt.figure(figsize=(10, 6))
sns.scatterplot(x='hum', y='cnt', data=data_hari, alpha=0.6, color = 'red')
plt.title('Hubungan antara Kelembaban dan Penggunaan Sepeda')
plt.xlabel('Kelembaban')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.grid()
plt.show()

#Scatterplot untuk hubungan antara kecepatan angin dan penggunaan sepeda
plt.figure(figsize=(10, 6))
sns.scatterplot(x='windspeed', y='cnt', data=data_hari, alpha=0.6, color = 'orange')
plt.title('Hubungan Kecepatan Angin dan Penggunaan Sepeda')
plt.xlabel('Kecepatan Angin')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.grid()
plt.show()

"""### Pertanyaan 3:"""

# Mengelompokkan data berdasarkan tanggal untuk melihat tren penggunaan dari waktu ke waktu
data_hari['dteday'] = pd.to_datetime(data_hari['dteday'])
tren = data_hari.groupby('dteday')['cnt'].sum().reset_index()

# Membuat Line Plot
plt.figure(figsize=(12, 6))
plt.plot(tren['dteday'], tren['cnt'], color='orange')
plt.title('Tren Penggunaan Sepeda dari Waktu ke Waktu')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Penggunaan Sepeda')
plt.xticks(rotation=45)
plt.grid()
plt.show()

# Mengubah kolom dteday menjadi tipe datetime
data_hari['dteday'] = pd.to_datetime(data_hari['dteday'])

# Mengelompokkan data berdasarkan tanggal untuk melihat tren penggunaan dari waktu ke waktu
tren = data_hari.groupby('dteday')['cnt'].sum().reset_index()

# Membuat scatter plot
plt.figure(figsize=(12, 6))
plt.scatter(tren['dteday'], tren['cnt'], color='purple')
plt.title('Penggunaan Sepeda dari Waktu ke Waktu', fontsize=16)
plt.xlabel('Tanggal', fontsize=14)
plt.ylabel('Jumlah Penggunaan Sepeda', fontsize=14)
plt.xticks(rotation=45)
plt.grid()
plt.show()

"""**Insight:**
- Penggunaan sepeda pada hari kerja cenderung lebih banyak dibandingkan dengan akhir pekan.
- Penggunaan sepeda pada musim gugur cenderung lebih banyak dari musim lainnya.
- Penggunaan sepeda dipengaruhi oleh cuaca dan suhu pada hari tersebut, ketika cuaca cerah maka pengguna sepeda akan lebih banyak dibandingkan ketika mendung ataupun hujan, begitu pula dengan suhu ketika suhu normal (tidak terlalu panas ataupun dingin) pengguna sepeda akan cenderung lebih banyak.
- Tren penggunaan sepeda meningkat dari bulan Januari hingga Juli 2011, kemudian terjadi penurunan pada bulan Oktober 2011 hingga Januari 2012, namun meningkat cukup signifikan pada Januari hingga April 2012, dan cukup konstan pada April hingga Oktober 2012, lalu terjadi penurunan di awal tahun 2013.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1 : Penggunaan sepeda pada hari libur tidak lebih banyak dari penggunaan pada hari kerja.
- Conclution pertanyaan 2 : Cuaca dan suhu memberikan pengaruh yang cukup signifikan pada permintaan penggunaan sepeda. Semakin cerah cuaca dan semakin normal suhu, permintaan pengguanaan sepeda semakin banyak. Kelembaban dan kecepatan angin tidak memberikan pengaruh yang signifikan pada permintaan penggunaan sepeda.
- Conclution pertanyaan 3: Tren permintaan penggunaan sepeda dari waktu ke waktu tidak selalu konstan, ada waktu dimana permintaan meningkat ataupun sebaliknya. Permintaan di akhir tahun cenderung menurun dan kembali meningkat ketika awal tahun.
"""